-- =============================================================================
-- ECX Visitor Management System — Schema Evolution (reference)
-- PostgreSQL 15+ | EF Core 10.0.9
-- =============================================================================
--
-- This script documents the INCREMENTAL schema changes applied by EF Core to
-- reach the current 21-table design. It mirrors the migration history recorded
-- in __EFMigrationsHistory (see docs/database_documentation.md §29). Each
-- numbered section below maps to one applied EF migration: MIGRATION 1 is the
-- InitialCreate base schema; MIGRATION 2–9 are the follow-up changes. The full
-- final schema is docs/visitor_management.sql.
--
-- NOTE: In the live database these changes were applied by `dotnet ef database
-- update`, NOT by running this script. This file is a documentation reference
-- of what each migration introduced.
-- =============================================================================

-- =============================================================================
-- MIGRATION 1 — 20260713082828_InitialCreate
-- =============================================================================
-- The base schema. Creates 19 of the 21 tables (the two later additions are
-- appointment_properties and checkout_items). Columns, types and constraints
-- for these tables match the corresponding sections of docs/visitor_management.sql.

CREATE TABLE departments (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(100) NOT NULL,
    description TEXT,
    location    VARCHAR(100),
    phone       VARCHAR(20),
    email       VARCHAR(100),
    is_active   BOOLEAN NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ,
    CONSTRAINT pk_departments PRIMARY KEY (id)
);

CREATE TABLE visitors (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY,
    full_name    VARCHAR(100) NOT NULL,
    phone        VARCHAR(20) NOT NULL,
    email        VARCHAR(100) NOT NULL,
    address      TEXT NOT NULL,
    national_id  VARCHAR(50),
    organization VARCHAR(100),
    gender       VARCHAR(10),
    photo_url    TEXT,
    is_active    BOOLEAN NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL,
    updated_at   TIMESTAMPTZ,
    CONSTRAINT pk_visitors PRIMARY KEY (id),
    CONSTRAINT uq_visitors_email UNIQUE (email)
);

CREATE TABLE users (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY,
    full_name     VARCHAR(100) NOT NULL,
    email         VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(50) NOT NULL,
    is_active     BOOLEAN NOT NULL,
    last_login    TIMESTAMPTZ,
    employee_id   INTEGER,
    visitor_id    INTEGER,
    created_at    TIMESTAMPTZ NOT NULL,
    updated_at    TIMESTAMPTZ,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT fk_users_visitors FOREIGN KEY (visitor_id)
        REFERENCES visitors (id) ON DELETE NO ACTION
);
CREATE UNIQUE INDEX uq_users_employee_id ON users (employee_id) WHERE employee_id IS NOT NULL;
CREATE UNIQUE INDEX uq_users_visitor_id ON users (visitor_id) WHERE visitor_id IS NOT NULL;

CREATE TABLE employees (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY,
    user_id       INTEGER,
    department_id INTEGER NOT NULL,
    full_name     VARCHAR(100) NOT NULL,
    email         VARCHAR(100) NOT NULL,
    phone         VARCHAR(20) NOT NULL,
    position      VARCHAR(100) NOT NULL,
    office_number VARCHAR(20),
    status        VARCHAR(20) NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL,
    updated_at    TIMESTAMPTZ,
    CONSTRAINT pk_employees PRIMARY KEY (id),
    CONSTRAINT uq_employees_email UNIQUE (email),
    CONSTRAINT fk_employees_departments FOREIGN KEY (department_id)
        REFERENCES departments (id) ON DELETE CASCADE,
    CONSTRAINT fk_employees_users FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE NO ACTION
);
CREATE UNIQUE INDEX uq_employees_user_id ON employees (user_id) WHERE user_id IS NOT NULL;

CREATE TABLE appointments (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY,
    visitor_id           INTEGER NOT NULL,
    employee_id          INTEGER NOT NULL,
    requested_date       DATE NOT NULL,
    requested_start_time TIMESTAMPTZ NOT NULL,
    requested_end_time   TIMESTAMPTZ NOT NULL,
    purpose              VARCHAR(500) NOT NULL,
    status               VARCHAR(30) NOT NULL,
    employee_response    TIMESTAMPTZ,
    approval_date        TIMESTAMPTZ,
    reminder_email_sent  BOOLEAN NOT NULL,
    reminder_sms_sent    BOOLEAN NOT NULL,
    visitor_confirmed    BOOLEAN NOT NULL,
    check_in_allowed     BOOLEAN NOT NULL,
    appointment_code     VARCHAR(20),
    is_confidential      BOOLEAN NOT NULL,
    delegated_to_employee_id INTEGER,
    original_employee_id      INTEGER,
    redirect_department_id    INTEGER,
    rejection_reason     TEXT,
    notes                TEXT,
    created_at           TIMESTAMPTZ NOT NULL,
    updated_at           TIMESTAMPTZ,
    CONSTRAINT pk_appointments PRIMARY KEY (id),
    CONSTRAINT fk_appointments_visitors FOREIGN KEY (visitor_id)
        REFERENCES visitors (id) ON DELETE RESTRICT,
    CONSTRAINT fk_appointments_employees FOREIGN KEY (employee_id)
        REFERENCES employees (id) ON DELETE RESTRICT,
    CONSTRAINT fk_appointments_delegated_employee FOREIGN KEY (delegated_to_employee_id)
        REFERENCES employees (id) ON DELETE RESTRICT,
    CONSTRAINT fk_appointments_original_employee FOREIGN KEY (original_employee_id)
        REFERENCES employees (id) ON DELETE RESTRICT,
    CONSTRAINT fk_appointments_redirect_department FOREIGN KEY (redirect_department_id)
        REFERENCES departments (id) ON DELETE RESTRICT
);

-- Other tables created by InitialCreate (see docs/visitor_management.sql):
--   visits, visitor_items, notifications, visitor_notifications,
--   reschedule_requests, appointment_comments, appointment_attachments,
--   employee_schedules, employee_unavailability, email_queue, sms_queue,
--   refresh_tokens, password_reset_tokens, audit_logs

-- =============================================================================
-- MIGRATION 2 — 20260731074958_AddRouteType
-- =============================================================================
-- Introduces the appointment routing concept: a visitor books directly with an
-- employee (DirectEmployee) or asks reception to route them (Reception).

ALTER TABLE appointments ADD COLUMN route_type VARCHAR(30);

-- =============================================================================
-- MIGRATION 3 — 20260731110014_AddAppointmentMethodAndAssignment
-- =============================================================================
-- Adds how the appointment was created (ReceptionAssistance / ScheduleMyself)
-- plus the reception assignment workflow columns (assigned department/employee,
-- assigner and timestamp, redirect source department and reason).

ALTER TABLE appointments
    ADD COLUMN appointment_method        VARCHAR(30),
    ADD COLUMN assigned_at               TIMESTAMPTZ,
    ADD COLUMN assigned_by               INTEGER,
    ADD COLUMN assigned_department_id    INTEGER,
    ADD COLUMN assigned_employee_id      INTEGER;

ALTER TABLE appointments
    ADD CONSTRAINT fk_appointments_assigned_department FOREIGN KEY (assigned_department_id)
        REFERENCES departments (id) ON DELETE NO ACTION,
    ADD CONSTRAINT fk_appointments_assigned_employee FOREIGN KEY (assigned_employee_id)
        REFERENCES employees (id) ON DELETE NO ACTION,
    ADD CONSTRAINT fk_appointments_redirected_from_department FOREIGN KEY (redirected_from_department_id)
        REFERENCES departments (id) ON DELETE NO ACTION;

CREATE INDEX ix_appointments_assigned_department_id ON appointments (assigned_department_id);
CREATE INDEX ix_appointments_assigned_employee_id ON appointments (assigned_employee_id);
CREATE INDEX ix_appointments_redirected_from_department_id ON appointments (redirected_from_department_id);

-- =============================================================================
-- MIGRATION 4 — 20260731195610_AddSupportingLetter
-- =============================================================================
-- Adds the single supporting-letter upload columns on appointments
-- (distinct from the later appointment_attachments table).

ALTER TABLE appointments
    ADD COLUMN attachment_file_name          VARCHAR(255),
    ADD COLUMN attachment_original_name      VARCHAR(255),
    ADD COLUMN attachment_content_type       VARCHAR(120),
    ADD COLUMN attachment_path               VARCHAR(500),
    ADD COLUMN attachment_size               BIGINT,
    ADD COLUMN attachment_uploaded_at        TIMESTAMPTZ;

-- =============================================================================
-- MIGRATION 5 — 20260804123642_AddAppointmentProperties
-- =============================================================================
-- Introduces the declared-property workflow: the appointment_properties table
-- and the property authorization letter upload columns on appointments.

ALTER TABLE appointments
    ADD COLUMN property_letter_file_name       VARCHAR(255),
    ADD COLUMN property_letter_original_name   VARCHAR(255),
    ADD COLUMN property_letter_content_type    VARCHAR(120),
    ADD COLUMN property_letter_path            VARCHAR(500),
    ADD COLUMN property_letter_size            BIGINT,
    ADD COLUMN property_letter_uploaded_at     TIMESTAMPTZ;

CREATE TABLE appointment_properties (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY,
    appointment_id   INTEGER NOT NULL,
    property_type    VARCHAR(100) NOT NULL,
    brand            VARCHAR(100),
    model            VARCHAR(100),
    serial_number    VARCHAR(100),
    asset_tag_number VARCHAR(100),
    quantity         INTEGER NOT NULL,
    description      TEXT,
    is_verified      BOOLEAN NOT NULL,
    verified_at      TIMESTAMPTZ,
    verified_by_user_id INTEGER,
    created_at       TIMESTAMPTZ NOT NULL,
    updated_at       TIMESTAMPTZ,
    CONSTRAINT pk_appointment_properties PRIMARY KEY (id),
    CONSTRAINT fk_appointment_properties_appointments FOREIGN KEY (appointment_id)
        REFERENCES appointments (id) ON DELETE CASCADE,
    CONSTRAINT fk_appointment_properties_verifier FOREIGN KEY (verified_by_user_id)
        REFERENCES users (id) ON DELETE RESTRICT
);
CREATE INDEX ix_appointment_properties_appointment_id ON appointment_properties (appointment_id);
CREATE INDEX ix_appointment_properties_is_verified ON appointment_properties (is_verified);
CREATE INDEX ix_appointment_properties_verified_by_user_id ON appointment_properties (verified_by_user_id);

-- =============================================================================
-- MIGRATION 6 — 20260804181825_AddVisitorPropertySelection
-- =============================================================================
-- Allows the visitor to declare whether they carry property items (has_properties
-- flag, default false) and to name their property item during booking (the
-- property_name column, empty-string default).

ALTER TABLE appointments ADD COLUMN has_properties BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE appointment_properties ADD COLUMN property_name VARCHAR(255) NOT NULL DEFAULT '';

-- =============================================================================
-- MIGRATION 7 — 20260804200407_AddUnavailabilityTimeAndRepeat
-- =============================================================================
-- Extends employee_unavailability with an intra-day time window and a repeat
-- rule (used by the calendar's Add Unavailability dialog).

ALTER TABLE employee_unavailability
    ADD COLUMN start_time TIME,
    ADD COLUMN end_time   TIME,
    ADD COLUMN repeat     VARCHAR(20);

-- =============================================================================
-- MIGRATION 8 — 20260805064924_AddPropertyVerificationStatus
-- =============================================================================
-- Adds an explicit verification state to property items, distinguishing a
-- verified item from an item that was found to be additional at check-in.

ALTER TABLE appointment_properties ADD COLUMN verification_status VARCHAR(50);

-- =============================================================================
-- MIGRATION 9 — 20260807065634_AddCheckoutItems
-- =============================================================================
-- Adds the check-out item-return workflow: the security officer records which
-- declared property items are returned before the visitor leaves.

CREATE TABLE checkout_items (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY,
    visit_id                INTEGER NOT NULL,
    appointment_property_id INTEGER,
    item_name               VARCHAR(255) NOT NULL,
    description             TEXT,
    quantity                INTEGER NOT NULL,
    return_status           VARCHAR(30) NOT NULL,
    remarks                 TEXT,
    created_at              TIMESTAMPTZ NOT NULL,
    updated_at              TIMESTAMPTZ,
    CONSTRAINT pk_checkout_items PRIMARY KEY (id),
    CONSTRAINT fk_checkout_items_visits FOREIGN KEY (visit_id)
        REFERENCES visits (id) ON DELETE CASCADE,
    CONSTRAINT fk_checkout_items_appointment_properties FOREIGN KEY (appointment_property_id)
        REFERENCES appointment_properties (id) ON DELETE SET NULL
);
CREATE INDEX ix_checkout_items_visit_id ON checkout_items (visit_id);
CREATE INDEX ix_checkout_items_appointment_property_id ON checkout_items (appointment_property_id);
