-- =============================================================================
-- ECX Visitor Management System — Full Database Schema (reference)
-- PostgreSQL 15+ | Matches the schema produced by the applied EF Core 10.0.9
-- migrations (see docs/database_documentation.md §29 Migration History).
-- =============================================================================
--
-- IMPORTANT
-- --------
-- * The production database is created and maintained by EF Core migrations
--   (dotnet ef database update). This script is a DOCUMENTATION reference that
--   reproduces the same tables, columns, types, defaults, FKs and indexes.
-- * There are NO native PostgreSQL ENUM types. All status/type/role fields are
--   stored as VARCHAR and validated in the application layer (backend/Models/
--   Enums.cs). Values such as 'Approved', 'Pending', 'Admin' are plain strings.
-- * All primary keys use GENERATED BY DEFAULT AS IDENTITY (not ALWAYS) so seed
--   scripts may insert explicit IDs.
-- * The ONLY non-null column defaults in the database are:
--     - appointments.has_properties                = false
--     - appointment_properties.property_name       = '' (empty string)
--   All other defaults are applied in application code.
--
-- Constraint naming in this file is clean and readable; the live database uses
-- EF Core's generated names (PK_<table>, FK_<table>_<target>_<column>,
-- IX_<table>_<column>, plus redundant "2200_*_not_null" CHECK constraints).
-- =============================================================================

BEGIN;

-- =============================================================================
-- 1. REFERENCE & IDENTITY
-- =============================================================================

CREATE TABLE departments (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(100) NOT NULL,
    description TEXT,
    location    VARCHAR(100),
    phone       VARCHAR(20),
    email       VARCHAR(100),
    is_active   BOOLEAN NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ,
    CONSTRAINT pk_departments PRIMARY KEY (id)
);

CREATE TABLE visitors (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    full_name   VARCHAR(100) NOT NULL,
    phone       VARCHAR(20) NOT NULL,
    email       VARCHAR(100) NOT NULL,
    address     TEXT NOT NULL,
    national_id VARCHAR(50),
    organization VARCHAR(100),
    gender      VARCHAR(10),
    photo_url   TEXT,
    is_active   BOOLEAN NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ,
    CONSTRAINT pk_visitors PRIMARY KEY (id),
    CONSTRAINT uq_visitors_email UNIQUE (email),
    CONSTRAINT uq_visitors_national_id UNIQUE (national_id)
);
CREATE INDEX ix_visitors_full_name ON visitors (full_name);

CREATE TABLE users (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY,
    full_name     VARCHAR(100) NOT NULL,
    email         VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(50) NOT NULL,
    is_active     BOOLEAN NOT NULL,
    last_login    TIMESTAMPTZ,
    employee_id   INTEGER,
    visitor_id    INTEGER,
    created_at    TIMESTAMPTZ NOT NULL,
    updated_at    TIMESTAMPTZ,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT fk_users_visitors FOREIGN KEY (visitor_id)
        REFERENCES visitors (id) ON DELETE NO ACTION
);
CREATE UNIQUE INDEX uq_users_employee_id ON users (employee_id) WHERE employee_id IS NOT NULL;
CREATE UNIQUE INDEX uq_users_visitor_id ON users (visitor_id) WHERE visitor_id IS NOT NULL;

CREATE TABLE employees (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY,
    full_name     VARCHAR(100) NOT NULL,
    phone         VARCHAR(20) NOT NULL,
    email         VARCHAR(100) NOT NULL,
    department_id INTEGER NOT NULL,
    position      VARCHAR(100) NOT NULL,
    office_number VARCHAR(20),
    status        VARCHAR(20) NOT NULL,
    user_id       INTEGER,
    created_at    TIMESTAMPTZ NOT NULL,
    updated_at    TIMESTAMPTZ,
    CONSTRAINT pk_employees PRIMARY KEY (id),
    CONSTRAINT uq_employees_email UNIQUE (email),
    CONSTRAINT fk_employees_departments FOREIGN KEY (department_id)
        REFERENCES departments (id) ON DELETE CASCADE,
    CONSTRAINT fk_employees_users FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE NO ACTION
);
CREATE INDEX ix_employees_department_id ON employees (department_id);
CREATE INDEX ix_employees_full_name ON employees (full_name);
CREATE UNIQUE INDEX uq_employees_user_id ON employees (user_id) WHERE user_id IS NOT NULL;

-- =============================================================================
-- 2. APPOINTMENTS & VISITS
-- =============================================================================

CREATE TABLE appointments (
    id                               INTEGER GENERATED BY DEFAULT AS IDENTITY,
    visitor_id                       INTEGER NOT NULL,
    employee_id                      INTEGER NOT NULL,
    requested_date                   DATE NOT NULL,
    requested_start_time             TIMESTAMPTZ NOT NULL,
    requested_end_time               TIMESTAMPTZ NOT NULL,
    purpose                          VARCHAR(500) NOT NULL,
    status                           VARCHAR(30) NOT NULL,
    route_type                       VARCHAR(30),
    appointment_method               VARCHAR(30),
    employee_response                TIMESTAMPTZ,
    approval_date                    TIMESTAMPTZ,
    rejection_reason                 TEXT,
    reminder_email_sent              BOOLEAN NOT NULL,
    reminder_sms_sent                BOOLEAN NOT NULL,
    visitor_confirmed                BOOLEAN NOT NULL,
    check_in_allowed                 BOOLEAN NOT NULL,
    appointment_code                 VARCHAR(20),
    is_confidential                  BOOLEAN NOT NULL,
    notes                            TEXT,
    delegated_to_employee_id         INTEGER,
    original_employee_id             INTEGER,
    redirect_department_id           INTEGER,
    redirected_from_department_id    INTEGER,
    redirect_reason                  TEXT,
    assigned_at                      TIMESTAMPTZ,
    assigned_by                      INTEGER,
    assigned_department_id           INTEGER,
    assigned_employee_id             INTEGER,
    has_properties                   BOOLEAN NOT NULL DEFAULT false,
    attachment_file_name             VARCHAR(255),
    attachment_original_name         VARCHAR(255),
    attachment_content_type          VARCHAR(120),
    attachment_path                  VARCHAR(500),
    attachment_size                  BIGINT,
    attachment_uploaded_at           TIMESTAMPTZ,
    property_letter_file_name        VARCHAR(255),
    property_letter_original_name    VARCHAR(255),
    property_letter_content_type     VARCHAR(120),
    property_letter_path             VARCHAR(500),
    property_letter_size             BIGINT,
    property_letter_uploaded_at      TIMESTAMPTZ,
    created_at                       TIMESTAMPTZ NOT NULL,
    updated_at                       TIMESTAMPTZ,
    CONSTRAINT pk_appointments PRIMARY KEY (id),
    CONSTRAINT fk_appointments_visitors FOREIGN KEY (visitor_id)
        REFERENCES visitors (id) ON DELETE RESTRICT,
    CONSTRAINT fk_appointments_employees FOREIGN KEY (employee_id)
        REFERENCES employees (id) ON DELETE RESTRICT,
    CONSTRAINT fk_appointments_original_employee FOREIGN KEY (original_employee_id)
        REFERENCES employees (id) ON DELETE RESTRICT,
    CONSTRAINT fk_appointments_delegated_employee FOREIGN KEY (delegated_to_employee_id)
        REFERENCES employees (id) ON DELETE RESTRICT,
    CONSTRAINT fk_appointments_assigned_employee FOREIGN KEY (assigned_employee_id)
        REFERENCES employees (id) ON DELETE NO ACTION,
    CONSTRAINT fk_appointments_redirect_department FOREIGN KEY (redirect_department_id)
        REFERENCES departments (id) ON DELETE RESTRICT,
    CONSTRAINT fk_appointments_assigned_department FOREIGN KEY (assigned_department_id)
        REFERENCES departments (id) ON DELETE NO ACTION,
    CONSTRAINT fk_appointments_redirected_from_department FOREIGN KEY (redirected_from_department_id)
        REFERENCES departments (id) ON DELETE NO ACTION
);
CREATE INDEX ix_appointments_visitor_id ON appointments (visitor_id);
CREATE INDEX ix_appointments_employee_id ON appointments (employee_id);
CREATE INDEX ix_appointments_requested_date ON appointments (requested_date);
CREATE INDEX ix_appointments_status ON appointments (status);
CREATE INDEX ix_appointments_appointment_code ON appointments (appointment_code);
CREATE INDEX ix_appointments_delegated_to_employee_id ON appointments (delegated_to_employee_id);
CREATE INDEX ix_appointments_original_employee_id ON appointments (original_employee_id);
CREATE INDEX ix_appointments_redirect_department_id ON appointments (redirect_department_id);
CREATE INDEX ix_appointments_redirected_from_department_id ON appointments (redirected_from_department_id);
CREATE INDEX ix_appointments_assigned_department_id ON appointments (assigned_department_id);
CREATE INDEX ix_appointments_assigned_employee_id ON appointments (assigned_employee_id);

CREATE TABLE visits (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY,
    visitor_id            INTEGER NOT NULL,
    employee_id           INTEGER NOT NULL,
    appointment_id        INTEGER,
    purpose               VARCHAR(500) NOT NULL,
    visit_date            DATE NOT NULL,
    check_in_time         TIMESTAMPTZ,
    check_out_time        TIMESTAMPTZ,
    status                VARCHAR(20) NOT NULL,
    badge_number          VARCHAR(50),
    security_officer      VARCHAR(100),
    remark                TEXT,
    is_destination_known  BOOLEAN NOT NULL,
    redirect_note         TEXT,
    created_at            TIMESTAMPTZ NOT NULL,
    updated_at            TIMESTAMPTZ,
    CONSTRAINT pk_visits PRIMARY KEY (id),
    CONSTRAINT fk_visits_visitors FOREIGN KEY (visitor_id)
        REFERENCES visitors (id) ON DELETE RESTRICT,
    CONSTRAINT fk_visits_employees FOREIGN KEY (employee_id)
        REFERENCES employees (id) ON DELETE RESTRICT,
    CONSTRAINT fk_visits_appointments FOREIGN KEY (appointment_id)
        REFERENCES appointments (id) ON DELETE SET NULL
);
CREATE INDEX ix_visits_visitor_id ON visits (visitor_id);
CREATE INDEX ix_visits_employee_id ON visits (employee_id);
CREATE INDEX ix_visits_appointment_id ON visits (appointment_id);
CREATE INDEX ix_visits_status ON visits (status);
CREATE INDEX ix_visits_visit_date ON visits (visit_date);
CREATE INDEX ix_visits_check_in_time ON visits (check_in_time);

-- =============================================================================
-- 3. APPOINTMENT CHILD TABLES
-- =============================================================================

CREATE TABLE appointment_properties (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY,
    appointment_id       INTEGER NOT NULL,
    property_type        VARCHAR(100) NOT NULL,
    property_name        VARCHAR(255) NOT NULL DEFAULT '',
    brand                VARCHAR(100),
    model                VARCHAR(100),
    serial_number        VARCHAR(100),
    asset_tag_number     VARCHAR(100),
    quantity             INTEGER NOT NULL,
    description          TEXT,
    is_verified          BOOLEAN NOT NULL,
    verification_status  VARCHAR(50),
    verified_at          TIMESTAMPTZ,
    verified_by_user_id  INTEGER,
    created_at           TIMESTAMPTZ NOT NULL,
    updated_at           TIMESTAMPTZ,
    CONSTRAINT pk_appointment_properties PRIMARY KEY (id),
    CONSTRAINT fk_appointment_properties_appointments FOREIGN KEY (appointment_id)
        REFERENCES appointments (id) ON DELETE CASCADE,
    CONSTRAINT fk_appointment_properties_verifier FOREIGN KEY (verified_by_user_id)
        REFERENCES users (id) ON DELETE RESTRICT
);
CREATE INDEX ix_appointment_properties_appointment_id ON appointment_properties (appointment_id);
CREATE INDEX ix_appointment_properties_is_verified ON appointment_properties (is_verified);
CREATE INDEX ix_appointment_properties_verified_by_user_id ON appointment_properties (verified_by_user_id);

CREATE TABLE appointment_comments (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY,
    appointment_id INTEGER NOT NULL,
    user_id        INTEGER NOT NULL,
    comment_text   TEXT NOT NULL,
    is_internal    BOOLEAN NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL,
    updated_at     TIMESTAMPTZ,
    CONSTRAINT pk_appointment_comments PRIMARY KEY (id),
    CONSTRAINT fk_appointment_comments_appointments FOREIGN KEY (appointment_id)
        REFERENCES appointments (id) ON DELETE CASCADE,
    CONSTRAINT fk_appointment_comments_users FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE RESTRICT
);
CREATE INDEX ix_appointment_comments_appointment_id ON appointment_comments (appointment_id);
CREATE INDEX ix_appointment_comments_user_id ON appointment_comments (user_id);

CREATE TABLE appointment_attachments (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY,
    appointment_id INTEGER NOT NULL,
    file_name      VARCHAR(255) NOT NULL,
    file_path      TEXT NOT NULL,
    file_size      INTEGER NOT NULL,
    content_type   VARCHAR(100) NOT NULL,
    uploaded_by    INTEGER NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_appointment_attachments PRIMARY KEY (id),
    CONSTRAINT fk_appointment_attachments_appointments FOREIGN KEY (appointment_id)
        REFERENCES appointments (id) ON DELETE CASCADE,
    CONSTRAINT fk_appointment_attachments_users FOREIGN KEY (uploaded_by)
        REFERENCES users (id) ON DELETE RESTRICT
);
CREATE INDEX ix_appointment_attachments_appointment_id ON appointment_attachments (appointment_id);
CREATE INDEX ix_appointment_attachments_uploaded_by ON appointment_attachments (uploaded_by);

CREATE TABLE reschedule_requests (
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY,
    appointment_id         INTEGER NOT NULL,
    requested_by_user_id   INTEGER NOT NULL,
    new_date               DATE NOT NULL,
    new_start_time         TIMESTAMPTZ NOT NULL,
    new_end_time           TIMESTAMPTZ NOT NULL,
    reason                 TEXT,
    status                 VARCHAR(20) NOT NULL,
    responded_by_user_id   INTEGER,
    responded_at           TIMESTAMPTZ,
    created_at             TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_reschedule_requests PRIMARY KEY (id),
    CONSTRAINT fk_reschedule_requests_appointments FOREIGN KEY (appointment_id)
        REFERENCES appointments (id) ON DELETE CASCADE,
    CONSTRAINT fk_reschedule_requests_requester FOREIGN KEY (requested_by_user_id)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_reschedule_requests_responder FOREIGN KEY (responded_by_user_id)
        REFERENCES users (id) ON DELETE SET NULL
);
CREATE INDEX ix_reschedule_requests_appointment_id ON reschedule_requests (appointment_id);
CREATE INDEX ix_reschedule_requests_requested_by_user_id ON reschedule_requests (requested_by_user_id);
CREATE INDEX ix_reschedule_requests_responded_by_user_id ON reschedule_requests (responded_by_user_id);

-- =============================================================================
-- 4. NOTIFICATIONS
-- =============================================================================

CREATE TABLE notifications (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY,
    employee_id       INTEGER NOT NULL,
    appointment_id    INTEGER,
    visitor_id        INTEGER,
    title             VARCHAR(200) NOT NULL,
    message           TEXT NOT NULL,
    notification_type VARCHAR(20) NOT NULL,
    priority          VARCHAR(10) NOT NULL,
    channel           VARCHAR(10) NOT NULL,
    is_read           BOOLEAN NOT NULL,
    read_at           TIMESTAMPTZ,
    created_at        TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_notifications PRIMARY KEY (id),
    CONSTRAINT fk_notifications_employees FOREIGN KEY (employee_id)
        REFERENCES employees (id) ON DELETE CASCADE,
    CONSTRAINT fk_notifications_appointments FOREIGN KEY (appointment_id)
        REFERENCES appointments (id) ON DELETE SET NULL,
    CONSTRAINT fk_notifications_visitors FOREIGN KEY (visitor_id)
        REFERENCES visitors (id) ON DELETE CASCADE
);
CREATE INDEX ix_notifications_employee_id ON notifications (employee_id);
CREATE INDEX ix_notifications_appointment_id ON notifications (appointment_id);
CREATE INDEX ix_notifications_visitor_id ON notifications (visitor_id);
CREATE INDEX ix_notifications_created_at ON notifications (created_at);

CREATE TABLE visitor_notifications (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY,
    visitor_id        INTEGER NOT NULL,
    appointment_id    INTEGER,
    title             VARCHAR(200) NOT NULL,
    message           TEXT NOT NULL,
    notification_type VARCHAR(20) NOT NULL,
    channel           VARCHAR(10) NOT NULL,
    is_read           BOOLEAN NOT NULL,
    read_at           TIMESTAMPTZ,
    created_at        TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_visitor_notifications PRIMARY KEY (id),
    CONSTRAINT fk_visitor_notifications_visitors FOREIGN KEY (visitor_id)
        REFERENCES visitors (id) ON DELETE CASCADE,
    CONSTRAINT fk_visitor_notifications_appointments FOREIGN KEY (appointment_id)
        REFERENCES appointments (id) ON DELETE SET NULL
);
CREATE INDEX ix_visitor_notifications_visitor_id ON visitor_notifications (visitor_id);
CREATE INDEX ix_visitor_notifications_appointment_id ON visitor_notifications (appointment_id);

-- =============================================================================
-- 5. SCHEDULING
-- =============================================================================

CREATE TABLE employee_schedules (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY,
    employee_id      INTEGER NOT NULL,
    day_of_week      VARCHAR(9) NOT NULL,
    start_time       TIME NOT NULL,
    end_time         TIME NOT NULL,
    break_start      TIME,
    break_end        TIME,
    is_available     BOOLEAN NOT NULL,
    max_appointments INTEGER NOT NULL,
    notes            TEXT,
    created_at       TIMESTAMPTZ NOT NULL,
    updated_at       TIMESTAMPTZ,
    CONSTRAINT pk_employee_schedules PRIMARY KEY (id),
    CONSTRAINT uq_employee_schedules_per_day UNIQUE (employee_id, day_of_week),
    CONSTRAINT fk_employee_schedules_employees FOREIGN KEY (employee_id)
        REFERENCES employees (id) ON DELETE CASCADE
);

CREATE TABLE employee_unavailability (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY,
    employee_id         INTEGER NOT NULL,
    unavailability_type VARCHAR(50) NOT NULL,
    start_date          DATE NOT NULL,
    end_date            DATE,
    start_time          TIME,
    end_time            TIME,
    repeat              VARCHAR(20),
    reason              TEXT,
    created_by          INTEGER NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL,
    updated_at          TIMESTAMPTZ,
    CONSTRAINT pk_employee_unavailability PRIMARY KEY (id),
    CONSTRAINT fk_employee_unavailability_employees FOREIGN KEY (employee_id)
        REFERENCES employees (id) ON DELETE CASCADE,
    CONSTRAINT fk_employee_unavailability_creator FOREIGN KEY (created_by)
        REFERENCES users (id) ON DELETE RESTRICT
);
CREATE INDEX ix_employee_unavailability_employee_id ON employee_unavailability (employee_id);
CREATE INDEX ix_employee_unavailability_created_by ON employee_unavailability (created_by);

-- =============================================================================
-- 6. ITEMS (check-in / check-out)
-- =============================================================================

CREATE TABLE visitor_items (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY,
    visit_id      INTEGER NOT NULL,
    item_name     VARCHAR(200) NOT NULL,
    quantity      INTEGER NOT NULL,
    serial_number VARCHAR(100),
    brand         VARCHAR(100),
    description   TEXT,
    is_verified   BOOLEAN NOT NULL,
    verified_at   TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL,
    updated_at    TIMESTAMPTZ,
    CONSTRAINT pk_visitor_items PRIMARY KEY (id),
    CONSTRAINT fk_visitor_items_visits FOREIGN KEY (visit_id)
        REFERENCES visits (id) ON DELETE CASCADE
);
CREATE INDEX ix_visitor_items_visit_id ON visitor_items (visit_id);

CREATE TABLE checkout_items (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY,
    visit_id                INTEGER NOT NULL,
    appointment_property_id INTEGER,
    item_name               VARCHAR(255) NOT NULL,
    description             TEXT,
    quantity                INTEGER NOT NULL,
    return_status           VARCHAR(30) NOT NULL,
    remarks                 TEXT,
    created_at              TIMESTAMPTZ NOT NULL,
    updated_at              TIMESTAMPTZ,
    CONSTRAINT pk_checkout_items PRIMARY KEY (id),
    CONSTRAINT fk_checkout_items_visits FOREIGN KEY (visit_id)
        REFERENCES visits (id) ON DELETE CASCADE,
    CONSTRAINT fk_checkout_items_appointment_properties FOREIGN KEY (appointment_property_id)
        REFERENCES appointment_properties (id) ON DELETE SET NULL
);
CREATE INDEX ix_checkout_items_visit_id ON checkout_items (visit_id);
CREATE INDEX ix_checkout_items_appointment_property_id ON checkout_items (appointment_property_id);

-- =============================================================================
-- 7. OUTBOUND QUEUES
-- =============================================================================
-- appointment_id in the queue tables is an APPLICATION reference only — there is
-- deliberately no FK so queue jobs survive appointment cleanup.

CREATE TABLE email_queue (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY,
    appointment_id  INTEGER,
    recipient_email VARCHAR(255) NOT NULL,
    subject         VARCHAR(255) NOT NULL,
    body            TEXT NOT NULL,
    status          VARCHAR(20) NOT NULL,
    retry_count     INTEGER NOT NULL,
    sent_at         TIMESTAMPTZ,
    error_message   TEXT,
    created_at      TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_email_queue PRIMARY KEY (id)
);

CREATE TABLE sms_queue (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY,
    appointment_id  INTEGER,
    recipient_phone VARCHAR(20) NOT NULL,
    message         TEXT NOT NULL,
    status          VARCHAR(20) NOT NULL,
    retry_count     INTEGER NOT NULL,
    sent_at         TIMESTAMPTZ,
    error_message   TEXT,
    created_at      TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_sms_queue PRIMARY KEY (id)
);

-- =============================================================================
-- 8. SECURITY TOKENS
-- =============================================================================

CREATE TABLE refresh_tokens (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    user_id     INTEGER NOT NULL,
    token       VARCHAR(500) NOT NULL,
    expires_at  TIMESTAMPTZ NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL,
    is_revoked  BOOLEAN NOT NULL,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id),
    CONSTRAINT uq_refresh_tokens_token UNIQUE (token),
    CONSTRAINT fk_refresh_tokens_users FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX ix_refresh_tokens_user_id ON refresh_tokens (user_id);

CREATE TABLE password_reset_tokens (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    email       VARCHAR(100) NOT NULL,
    token       VARCHAR(500) NOT NULL,
    expires_at  TIMESTAMPTZ NOT NULL,
    is_used     BOOLEAN NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_password_reset_tokens PRIMARY KEY (id),
    CONSTRAINT uq_password_reset_tokens_token UNIQUE (token)
);

-- =============================================================================
-- 9. AUDIT
-- =============================================================================

CREATE TABLE audit_logs (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    user_id     INTEGER NOT NULL,
    action      VARCHAR(100) NOT NULL,
    entity_name VARCHAR(100) NOT NULL,
    entity_id   INTEGER NOT NULL,
    old_values  TEXT,
    new_values  TEXT,
    ip_address  VARCHAR(45),
    user_agent  TEXT,
    created_at  TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_audit_logs PRIMARY KEY (id),
    CONSTRAINT fk_audit_logs_users FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE RESTRICT
);
CREATE INDEX ix_audit_logs_user_id ON audit_logs (user_id);
CREATE INDEX ix_audit_logs_entity ON audit_logs (entity_name, entity_id);
CREATE INDEX ix_audit_logs_created_at ON audit_logs (created_at);

-- =============================================================================
-- 10. EF CORE MIGRATION HISTORY (for reference; created automatically)
-- =============================================================================

CREATE TABLE "__EFMigrationsHistory" (
    "MigrationId"    VARCHAR(150) NOT NULL,
    "ProductVersion" VARCHAR(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

COMMIT;
